#!/bin/bash --login

# This is a PBS script for the Tier2 system Cirrus

# PBS job options (name, compute nodes, job time)
#PBS -A y15
#PBS -N sharpen
#PBS -l walltime=00:01:00
#PBS -l place=excl
#PBS -l select=1:ncpus=36

module load intel-compilers-18

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

# Set the number of threads to 4

export OMP_NUM_THREADS=4

# Launch the parallel job
./sharpen
